// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_well_known_lnurlp_username_ from "./routes/.well-known/lnurlp/[username].ts";
import * as $_well_known_nostr_json from "./routes/.well-known/nostr.json.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_blog_like_slug_ from "./routes/api/blog/like/[slug].ts";
import * as $api_commit from "./routes/api/commit.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_kv from "./routes/api/kv.ts";
import * as $api_likes from "./routes/api/likes.ts";
import * as $api_projects from "./routes/api/projects.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $api_track from "./routes/api/track.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $branding_x_cover from "./routes/branding/x/cover.tsx";
import * as $branding_x_profile from "./routes/branding/x/profile.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $cv from "./routes/cv.tsx";
import * as $cv_pdf from "./routes/cv/pdf.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $lightning_callback_username_ from "./routes/lightning/callback/[username].ts";
import * as $projects from "./routes/projects.tsx";
import * as $projects_id_ from "./routes/projects/[id].tsx";
import * as $stats from "./routes/stats.tsx";
import * as $webstats from "./routes/webstats.tsx";
import * as $webstats_index from "./routes/webstats/index.tsx";
import * as $AboutPage from "./islands/AboutPage.tsx";
import * as $CVPage from "./islands/CVPage.tsx";
import * as $ContactPage from "./islands/ContactPage.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $ProjectPageTracker from "./islands/ProjectPageTracker.tsx";
import * as $ProjectsList from "./islands/ProjectsList.tsx";
import * as $Router from "./islands/Router.tsx";
import * as $SocialActions from "./islands/SocialActions.tsx";
import * as $StatsLink from "./islands/StatsLink.tsx";
import * as $StatsPage from "./islands/StatsPage.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import * as $WebStats from "./islands/WebStats.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/.well-known/lnurlp/[username].ts": $_well_known_lnurlp_username_,
    "./routes/.well-known/nostr.json.ts": $_well_known_nostr_json,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/blog/like/[slug].ts": $api_blog_like_slug_,
    "./routes/api/commit.ts": $api_commit,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/kv.ts": $api_kv,
    "./routes/api/likes.ts": $api_likes,
    "./routes/api/projects.ts": $api_projects,
    "./routes/api/stats.ts": $api_stats,
    "./routes/api/track.ts": $api_track,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/branding/x/cover.tsx": $branding_x_cover,
    "./routes/branding/x/profile.tsx": $branding_x_profile,
    "./routes/contact.tsx": $contact,
    "./routes/cv.tsx": $cv,
    "./routes/cv/pdf.ts": $cv_pdf,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/lightning/callback/[username].ts": $lightning_callback_username_,
    "./routes/projects.tsx": $projects,
    "./routes/projects/[id].tsx": $projects_id_,
    "./routes/stats.tsx": $stats,
    "./routes/webstats.tsx": $webstats,
    "./routes/webstats/index.tsx": $webstats_index,
  },
  islands: {
    "./islands/AboutPage.tsx": $AboutPage,
    "./islands/CVPage.tsx": $CVPage,
    "./islands/ContactPage.tsx": $ContactPage,
    "./islands/Footer.tsx": $Footer,
    "./islands/HomePage.tsx": $HomePage,
    "./islands/LikeButton.tsx": $LikeButton,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/ProjectPageTracker.tsx": $ProjectPageTracker,
    "./islands/ProjectsList.tsx": $ProjectsList,
    "./islands/Router.tsx": $Router,
    "./islands/SocialActions.tsx": $SocialActions,
    "./islands/StatsLink.tsx": $StatsLink,
    "./islands/StatsPage.tsx": $StatsPage,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
    "./islands/WebStats.tsx": $WebStats,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
