// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AboutPage from "./islands/AboutPage.tsx";
import * as $BlogPage from "./islands/BlogPage.tsx";
import * as $CVPage from "./islands/CVPage.tsx";
import * as $ContactPage from "./islands/ContactPage.tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $Router from "./islands/Router.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $_path_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AboutPage.tsx": $AboutPage,
    "./islands/BlogPage.tsx": $BlogPage,
    "./islands/CVPage.tsx": $CVPage,
    "./islands/ContactPage.tsx": $ContactPage,
    "./islands/HomePage.tsx": $HomePage,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/Router.tsx": $Router,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
