// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog from "./routes/blog.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $cv from "./routes/cv.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog.tsx": $blog,
    "./routes/contact.tsx": $contact,
    "./routes/cv.tsx": $cv,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
